learning_templates/basic_app/urls.py
from django.urls import path
from . import views


# TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
    path('',views.index,name ='index'),
    path('other',views.other,name ='other'),
    path('relative',views.relative, name = 'relative'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('basic_app.urls')),
    path('other/',include('basic_app.urls')),
    path('relative/',include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text': 'hello world','number':100}
    return render(request,'basic_app/index.html',context_dict)


def other(request):
    return render(request,'basic_app/other.html')


def relative(request):
    return render(request,'basic_app/relative_url.html') 

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
        <ul class="nav navbar-nav">
            <li><a href="{% url 'basic_app:index' %}" class="navbar-brand">BRAND</a></li>
            <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>
            <li><a href="{% url 'basic_app:other' %}" class="navbar-link">Other</a></li>

        </ul>

        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        <!--Anything outside this block will be inherited if you extend -->
        {% endblock %}

    </div>
</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
    {% block body_block %}
    <h1>WELCOME TO THE INDEX PAGE</h1>
    <h2>This is the index page showing</h2>
    <h1>{{ text|cut:'hello' }}</h1>
    <h2>{{ number|add:"1000 " }} </h2>


    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{% block body_block %}
    <h1>WELCOME TO THE OTHER PAGE</h1>
    <h2> This is an example of templaate inheritance</h2>
    {% endblock %}

learning_templates/templates/basic_app/relative_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Relative Url</title>
</head>
<body>
    <h1>WELCOME TO THE RELATIVE URL TEMPLATE PAGE </h1>
    <a href="{% url 'basic_app:other' %}"> THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}"> LINK TO ADMIN</a>
    <a href="{% url 'basic_app:index' %}"> LINK TO HOME PAGE</a>
</body>
</html>